Views
Rayan84/blog-rails pull request #5
Opened 2022-02-11 15:24 UTC by Rayan84

In this branch, the following content and features were added:

- View for users index, users show, posts index and posts show
- Logic to loop or filter the rendered data
- Style for the above mentioned view templates

2022-02-11 17:14 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️

### Hello @Rayan84  ✋🏼 
#### Your project is great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.

___ 

### 💯  Nice to have 💯
- Your git-flow is correct ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️


___


### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._

___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] If you create example users, posts, comments in the `db/seeds.rb`  file that will be great. You can just migrate the seed and test it on the page.

___

### Cheers and Happy coding! 💻 👏

![almost](https://media.giphy.com/media/oHwvp6bEuiog0bxg2P/giphy.gif)

___

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_


_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mentioning me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._
___
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-02-11 17:14 UTC, ahmetbozaci commented on app/views/users/show.html.erb
> +    <button class="see-all-posts-button">See all posts</button>
- [x] The button is not working. When ı click the see all posts button ı have to see the user's post as displayed on the wireframe. Please fix it.

**I can see users like in the wireframe, ı can click every user on the homepage, ı can see most recent posts after clicking the user. These are very good. But;**

- [x] You don't have to page that shows all posts after clicking the button. After creating this page you should also display `5 recent comments` as in the wireframe. 

![image](https://user-images.githubusercontent.com/38635158/153630485-3ed7181f-c230-41c6-a644-2573c50d31b6.png)

- [x] Also, ı have to click every post on the page and see like wireframe
![image](https://user-images.githubusercontent.com/38635158/153632433-517eee31-1c1f-4433-a88b-f1e6a8e52d8d.png)

2022-02-11 17:14 UTC, ahmetbozaci commented on app/assets/stylesheets/users_show.css
> +  padding-bottom: 8px;
### OPTIONAL

- [x] For DRY CSS you can merge them in one padding.
- [More information about DRY principles](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/) 

- [Html and css best practices in curriculum](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-02-12 09:57 UTC, Emmyn5600 approved these changes
Hi @Rayan84 

STATUS: APPROVED :partying_face: 

Wooow👏, Your project is complete!  There is nothing else to say other than... it's time to merge it. 👏

Congratulations! 🎉 

Optional suggestions

-N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-02-12 09:58 UTC, merged